---
title: "Tables for the police transport perspective article"
author: "Cal Chengqi Fang"
date: "2024-07-29"
output: pdf_document
classoption: landscape
header-includes:
  - \setlength{\parindent}{2.5em}
  - \setlength{\parskip}{0em}
knit: >
  (function(inputFile, encoding){rmarkdown::render(inputFile, encoding=encoding, output_file="results/analysisResults.pdf")}) 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      warning=FALSE)
rm(list = ls())

require(tidyverse)
require(data.table)
require(googlesheets4)

require(knitr)      # For generating nice and organized results
require(kableExtra) # For generating nice and organized results
```

```{r data prep, include=FALSE}
# Read google sheets data into R
final <- read_sheet("https://docs.google.com/spreadsheets/d/1w_BaFUAuatmUQBt3qtRBzhm9tTDV4B9lRjTGTq79bAg")
# You would need to go through the authorization process here. More details can be found here:
# https://www.digitalocean.com/community/tutorials/google-sheets-in-r
#
# If you have any error accessing this Google sheet after a long while, please consider redo
# the authorization by running:
# gs4_auth()

fwrite(final, "data/interm/recordsLabeled.csv")
final <- fread("data/interm/recordsLabeled.csv")

# Replace NYC boroughs with NYC
final$City.Or.County[final$City.Or.County=="Bronx"] <- "NYC"
final$City.Or.County[final$City.Or.County=="Brooklyn"] <- "NYC"
final$City.Or.County[final$City.Or.County=="Corona (Queens)"] <- "NYC"
final$City.Or.County[final$City.Or.County=="New York (Manhattan)"] <- "NYC"
final$City.Or.County[final$City.Or.County=="Staten Island"] <- "NYC"

# Combine city name and state name
final$GEO <- str_c(final$City.Or.County, ", ", append(state.abb, "DC")[match(final$State, append(state.name, "District of Columbia"))])

# Drop suicide case
finalNoSuicide <- final %>% 
  filter(!grepl("Suicide", Detail, ignore.case=TRUE))

# Drop cities with higher than 30% Unknown
unknownSummary <- finalNoSuicide %>% 
  group_by(GEO, Response.Type) %>% 
  summarise(Count = n()) %>%
  pivot_wider(names_from = Response.Type, values_from = Count) %>% 
  mutate(Total = sum(c(Unknown, `Police Self-transfer`, Others, Ambulance), na.rm=TRUE)) %>% 
  filter(Unknown < 0.30*Total | is.na(Unknown))

final70 <- finalNoSuicide %>% 
  filter(GEO %in% unknownSummary$GEO) %>% 
  mutate(Year = format(Incident.Date, "%Y")) %>% 
  mutate(across(all_of(c("GEO","Response.Type")), as.factor)) %>% 
  rename(City = GEO)
```

```{r}
# Number of cases identified from GVA after cleaning
numFinal <- nrow(final)
# Number of cities with more than 10 cases
numCity <- length(unique(final$City.Or.County))
# Number of cities kept for table 1
numCity2 <- length(unique(final70$City.Or.County))

# Number of people with confirmed transport mode info
numConfirmed <- nrow(filter(final, Response.Type != "Unknown"))
# Number of people with confirmed transport mode info and shot by other people
numNoSuicide <- nrow(finalNoSuicide)
# Number of people kept for table 1
numTab1 <- nrow(final70)

# Summarize after dropping the suicide cases
summary <- finalNoSuicide %>% 
  group_by(Response.Type) %>% 
  summarize(Prop = round(n() / nrow(finalNoSuicide) * 100, 1)) %>% 
  pivot_wider(names_from="Response.Type",
              values_from="Prop") %>% 
  rename(Police = `Police Self-transfer`)

# Take out the two example cities
philly <- finalNoSuicide %>% 
  filter(GEO == "Philadelphia, PA") %>% 
  group_by(Response.Type) %>% 
  summarize(Num = n()) %>% 
  pivot_wider(names_from="Response.Type",
              values_from="Num") %>% 
  rename(Police = `Police Self-transfer`)

if (!("Ambulance" %in% colnames(philly))) {
  philly$Ambulance <- 0
}

huston <- finalNoSuicide %>% 
  filter(GEO == "Houston, TX") %>% 
  group_by(Response.Type) %>% 
  summarize(Num = n()) %>% 
  pivot_wider(names_from="Response.Type",
              values_from="Num") %>% 
  rename(Police = `Police Self-transfer`)

# Summarize the cities that mainly using one mode
cities <- unknownSummary
cities[is.na(cities)] <- 0.00
cityPolice <- sum(cities$`Police Self-transfer` > cities$Ambulance)
cityAmbulance <- sum(cities$Ambulance > cities$`Police Self-transfer`)
```

\newpage
# Table. Transport mode of police after sustaining firearm injuries by city between April 30, 2018-April 30, 2024
```{r prep tab1, message=FALSE, echo=FALSE}
# Summarize the total number of police shot by city
total <- final70 %>% 
  group_by(City, Response.Type) %>% 
  summarise(Count = n()) %>% 
  pivot_wider(names_from = Response.Type,
              values_from = Count) %>% 
  ungroup() %>% 
  mutate(Total = rowSums(select_if(., is.numeric), na.rm=TRUE)) %>% 
  select(City, Total)

# Summarize the transport mode proportion by city
prop <- final70 %>% 
  group_by(City, Response.Type) %>% 
  summarise(Count = n()) %>% 
  mutate(Prop = round(Count / sum(Count) * 100, 1),
         Report = paste0(Count, " (", Prop, ")")) %>% 
  select(-Count, -Prop) %>% 
  pivot_wider(names_from = Response.Type,
              values_from = Report)

# Merge the total number and transport mode proportion
tab1 <- prop %>% 
  merge(total) %>% 
  arrange(desc(Total)) %>% 
  select(City, Total, `Police Self-transfer`, Ambulance, Others, Unknown)

tab1End <- final70 %>% 
  group_by(Response.Type) %>% 
  summarise(Count = n()) %>% 
  mutate(Prop = round(Count / sum(Count) * 100, 1),
         Report = paste0(Count, " (", Prop, ")")) %>% 
  select(-Count, -Prop) %>% 
  pivot_wider(names_from = Response.Type,
              values_from = Report) %>% 
  mutate(City = "Total", 
         Total = nrow(final70)) %>% 
  select(City, Total, `Police Self-transfer`, Ambulance, Others, Unknown)

tab1 <- rbindlist(list(tab1, tab1End), fill=TRUE)

# Replace NA with 0
tab1[is.na(tab1)] <- "0 (0.0)"

# Prepare the footnote symbols
names(tab1) <- c("City", "Total police with firearm injuries", "Police vehicle", "Ambulance", "Other", "Unknown")
names(tab1)[1] <- paste0(names(tab1)[1], 
                         footnote_marker_alphabet(1))
names(tab1)[2] <- paste0(names(tab1)[2], 
                         footnote_marker_alphabet(2))
names(tab1)[5] <- paste0(names(tab1)[3], 
                         footnote_marker_alphabet(3))
```

```{r tab1, message=FALSE, echo=FALSE}
tab1  %>% 
  kbl(align="lccccc", booktabs=TRUE, escape=FALSE) %>% 
  kable_styling(latex_options = c("hold_position")) %>%
  add_header_above(header=c("", "", "Transport mode (No. (%))"=4)) %>% 
  footnote(alphabet = c("We utilized the Gun Violence Archive to identify 27 cities where more than 10 police were shot between April 30th, 2018 and April 30th, 2024. We then conducted extensive media research—reviewing news reports, police press releases, and videos—to determine how these individuals were transported to a hospital. Our process required review by two researchers and any discrepancies were resolved through discussion or referred to a third analyst for adjudication. We kept only cities for which we could ascertain the mode of transport for at least 70% of police, which left us with 18 cities.",
                        "Suicide cases, where officers were often found already deceased, were excluded. ",
                        "`Other’ includes instances where police were transported by air ambulance or deemed not requiring hospital transport."),
           threeparttable=TRUE)
```

\newpage
# Other tables - left out

## Simple outcome comparsion across different transport mode
```{r tab leftout1, message=FALSE, echo=FALSE}
# Summarize the outcome by transport mode
tabTemp <- final70 %>% 
  filter(Response.Type %in% c("Police Self-transfer", "Ambulance")) %>% 
  group_by(Response.Type, Outcome) %>% 
  summarize(num = n()) %>% 
  pivot_wider(names_from="Outcome", values_from="num") %>% 
  mutate(total = Injured + Killed, 
         propInjured = round(Injured / total * 100, 1),
         propKilled = round(Killed / total * 100, 1)) %>% 
  select(Response.Type, propInjured, propKilled, total)

kable(tabTemp, label="drop", col.names=c("Transport mode", "Injured (%)", "Killed (%)", "Total shot"))
```

## Simple outcome comparsion across different transport mode (without Philadelphia)
```{r tab leftout2, message=FALSE, echo=FALSE}
# Summarize the outcome by transport mode
tabTemp <- final70 %>% 
  filter(City.Or.County != "Philadelphia") %>% 
  filter(Response.Type %in% c("Police Self-transfer", "Ambulance")) %>% 
  group_by(Response.Type, Outcome) %>% 
  summarize(num = n()) %>% 
  pivot_wider(names_from="Outcome", values_from="num") %>% 
  mutate(total = Injured + Killed, 
         propInjured = round(Injured / total * 100, 1),
         propKilled = round(Killed / total * 100, 1)) %>% 
  select(Response.Type, propInjured, propKilled, total)

kable(tabTemp, label="drop", col.names=c("Transport mode", "Injured (%)", "Killed (%)", "Total shot"))
```

## Temporal and geographic variations
```{r tab leftout3, message=FALSE, echo=FALSE}
# Summarize the transport mode used by year
tabTemp <- finalNoSuicide %>% 
  mutate(Year = lubridate::year(Incident.Date)) %>% 
  group_by(Response.Type, Year) %>% 
  summarize(num = n()) %>% 
  pivot_wider(names_from="Year", values_from="num") %>% 
  rename(`Transport mode` = Response.Type)

kable(tabTemp, label="drop2")
```


